# Generated by Django 3.2.4 on 2021-12-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_bulletin'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_bulletin',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Bulletin',
        ),
    ]
